//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmAddEmployeeType
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Log
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Audit_Log()
        {
            this.Audit_Create_Delete = new HashSet<Audit_Create_Delete>();
            this.Audit_Update = new HashSet<Audit_Update>();
        }
    
        public int Audit_Log_Id { get; set; }
        public string Table_Name { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public Nullable<System.TimeSpan> User_Time { get; set; }
        public Nullable<int> Employee_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Audit_Create_Delete> Audit_Create_Delete { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Audit_Update> Audit_Update { get; set; }
    }
}
