//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmAddEmployeeType
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Purchase_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client_Purchase_Order()
        {
            this.Client_Purchase_Order_Line = new HashSet<Client_Purchase_Order_Line>();
        }
    
        public int Client_Purchase_Id { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<decimal> Gross_Amount { get; set; }
        public Nullable<int> Payment_Terms_ID { get; set; }
        public Nullable<int> Purchase_Order_Status_ID { get; set; }
        public Nullable<int> Supplier_Order_Id { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> Dispatch_Type_Id { get; set; }
        public Nullable<int> Dispatch_Id { get; set; }
        public string PO_Number { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Purchase_Order_Line> Client_Purchase_Order_Line { get; set; }
        public virtual Dispatch_Type Dispatch_Type { get; set; }
        public virtual Dispatch Dispatch { get; set; }
        public virtual Payment_Term Payment_Term { get; set; }
        public virtual Purchase_Order_Status Purchase_Order_Status { get; set; }
        public virtual Supplier_Order Supplier_Order { get; set; }
    }
}
