//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmAddEmployeeType
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Information
    {
        public int Company_Id { get; set; }
        public string Company_Name { get; set; }
        public string Company_Address { get; set; }
        public Nullable<long> VAT_Number { get; set; }
        public Nullable<decimal> VAT_Percentage { get; set; }
        public string Registration_Number { get; set; }
        public string Email_Address { get; set; }
        public string Telephone_Number { get; set; }
    }
}
