//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmAddEmployeeType
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit_Approval
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Credit_Approval()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int Credit_Approval_ID { get; set; }
        public Nullable<decimal> Credit_Approval_Amount { get; set; }
        public string Authourised_By { get; set; }
        public Nullable<System.DateTime> Date_Of_Commencement { get; set; }
        public Nullable<int> Credit_Status_ID { get; set; }
        public string Credit_Approval_Form { get; set; }
        public string CA_Number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
        public virtual Credit_Status Credit_Status { get; set; }
    }
}
