//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmAddEmployeeType
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit_Return_Line
    {
        public int Credit_Return_Line_ID { get; set; }
        public Nullable<int> Quantity_Returned { get; set; }
        public Nullable<int> Reason_For_Return_ID { get; set; }
        public Nullable<decimal> Credit_Return_Amount { get; set; }
        public Nullable<int> Credit_Return_ID { get; set; }
        public Nullable<int> Client_Purchase_Order_Line_ID { get; set; }
    
        public virtual Client_Purchase_Order_Line Client_Purchase_Order_Line { get; set; }
        public virtual Credit_Return Credit_Return { get; set; }
        public virtual Reason_For_Return Reason_For_Return { get; set; }
    }
}
