//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmAddEmployeeType
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refund_Line
    {
        public int Refund_Line_ID { get; set; }
        public Nullable<int> Refund_Quantity { get; set; }
        public Nullable<decimal> Refund_Amount { get; set; }
        public Nullable<int> Sales_Order_Line_ID { get; set; }
        public Nullable<int> Sale_Refund_ID { get; set; }
    
        public virtual Sale_Refund Sale_Refund { get; set; }
        public virtual Sales_Order_line Sales_Order_line { get; set; }
    }
}
