//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmAddEmployeeType
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Order_Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier_Order_Line()
        {
            this.Backorder_Line = new HashSet<Backorder_Line>();
        }
    
        public int Quantity { get; set; }
        public int Supplier_Order_Line_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Supplier_Order_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Backorder_Line> Backorder_Line { get; set; }
        public virtual Product Product { get; set; }
        public virtual Supplier_Order Supplier_Order { get; set; }
    }
}
