//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmAddEmployeeType
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Backorder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier_Backorder()
        {
            this.Backorder_Line = new HashSet<Backorder_Line>();
        }
    
        public int Supplier_Backorder_Id { get; set; }
        public Nullable<System.DateTime> Backorder_Date { get; set; }
        public Nullable<int> Backorder_Status_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Backorder_Line> Backorder_Line { get; set; }
        public virtual Backorder_Status Backorder_Status { get; set; }
    }
}
